name: Deploy

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: yarn build
      - name: Deploy
        run: yarn deploy
        
